# Generated by Django 4.2.3 on 2023-07-22 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
