# Generated by Django 4.2.3 on 2023-07-22 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0002_questions_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="user",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
