# Generated by Django 4.2.3 on 2023-07-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0005_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questions",
            name="uuid",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
