# Generated by Django 4.2.3 on 2023-07-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0008_userresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userresponse",
            name="user",
        ),
    ]
