# Generated by Django 4.2.3 on 2023-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0009_remove_userresponse_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userresponse",
            name="form_uid",
            field=models.CharField(default="sanyamjain", max_length=300),
        ),
    ]
