# Generated by Django 4.2.3 on 2023-07-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0011_userresponse_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_uid", models.CharField(default="sanyamjain", max_length=300)),
                ("questions", models.JSONField()),
            ],
        ),
    ]
