# Generated by Django 4.2.3 on 2023-07-23 02:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pope", "0012_form"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="form_uid",
            field=models.CharField(default=uuid.uuid4, max_length=300, unique=True),
        ),
    ]
